AWSTemplateFormatVersion: '2010-09-09'
Description: 'EBSボリュームを作成し、EC2インスタンスにアタッチします。'

Parameters:
  InstanceId:
    Type: AWS::EC2::Instance::Id
    Description: EC2 Instance ID
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Availability Zone

Resources:
  EBSVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 10
      VolumeType: gp3
      AvailabilityZone: !Ref AvailabilityZone
      Encrypted: true
      Tags:
        - Key: Name
          Value: my-ebs-volume

  VolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref InstanceId
      VolumeId: !Ref EBSVolume
      Device: /dev/sdf

Outputs:
  VolumeId:
    Description: EBS Volume ID
    Value: !Ref EBSVolume
