AWSTemplateFormatVersion: '2010-09-09'
Description: 'インターネットゲートウェイを作成し、VPCにアタッチします。'

Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: my-igw

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPCId

Outputs:
  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !Ref InternetGateway
