AWSTemplateFormatVersion: '2010-09-09'
Description: 'SQSキューを作成し、メッセージを送受信できるようにします。'

Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: my-queue
      VisibilityTimeoutSeconds: 30
      MessageRetentionPeriod: 345600
      ReceiveMessageWaitTimeSeconds: 0

Outputs:
  QueueURL:
    Description: SQS Queue URL
    Value: !Ref SQSQueue
  QueueArn:
    Description: SQS Queue ARN
    Value: !GetAtt SQSQueue.Arn
