AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodeBuildプロジェクトを作成し、ソースコードをビルドします。'

Parameters:
  RepositoryName:
    Type: String
    Description: CodeCommit Repository Name

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: 'arn:aws:s3:::/*'

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: my-build-project
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
      Source:
        Type: CODECOMMIT
        Location: !Sub 'https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${RepositoryName}'
        BuildSpec: buildspec.yml

Outputs:
  ProjectName:
    Description: CodeBuild Project Name
    Value: !Ref CodeBuildProject
