AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step Functionsステートマシンを作成し、複数のLambda関数を順次実行するワークフローを構築します。'

Parameters:
  LambdaFunctionArn:
    Type: String
    Description: Lambda Function ARN

Resources:
  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Ref LambdaFunctionArn

  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: my-state-machine
      RoleArn: !GetAtt StepFunctionsRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "A simple workflow",
          "StartAt": "HelloWorld",
          "States": {
            "HelloWorld": {
              "Type": "Task",
              "Resource": "${LambdaFunctionArn}",
              "End": true
            }
          }
        }

Outputs:
  StateMachineArn:
    Description: Step Functions State Machine ARN
    Value: !Ref StateMachine
