AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDSデータベースインスタンス（MySQL）を作成し、アプリケーションから接続できるようにします。'

Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet IDs (at least 2 subnets in different AZs)
  MasterUsername:
    Type: String
    Default: admin
    Description: Master username
  MasterUserPassword:
    Type: String
    NoEcho: true
    Description: Master user password

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: my-db-subnet-group
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: Name
          Value: my-db-subnet-group

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: rds-sg
      GroupDescription: Security group for RDS
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/16
          Description: MySQL access from VPC
      Tags:
        - Key: Name
          Value: rds-sg

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: my-rds-instance
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: '8.0'
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      AllocatedStorage: 20
      StorageType: gp3
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref SecurityGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      Tags:
        - Key: Name
          Value: my-rds-instance

Outputs:
  DBEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
  DBPort:
    Description: RDS Port
    Value: !GetAtt RDSInstance.Endpoint.Port
